#setup.jl
using Pkg; using Pkg.API
# Pkg.add("BenchmarkTools")
# Pkg.add("DistributedArrays")
# Pkg.add("Distributions")
# Pkg.add("FileIO")
# Pkg.add("Flux")
# Pkg.add("HDF5")
# Pkg.add("IterativeSolvers")
# Pkg.add("JLD2")
# Pkg.add("MultivariateStats")
# Pkg.add("PyPlot")
# # Pkg.add("SharedArrays")
# # Pkg.add("SpecialFunctions")
# Pkg.add("SymEngine")
# Pkg.add("Test")
# Pkg.add("Unitful")
# Pkg.add("UnitfulAstro")
# Pkg.add("Memoize")

# Pkg.add("CUDAdrv")
# Pkg.add("CUDAnative")
# Pkg.add("CuArrays")
# Pkg.add("GPUArrays")

Pkg.activate(".")
Pkg.instantiate()
Pkg.update()
Pkg.API.precompile()
